---
deployment:
  tasks:
    - current_path=`pwd` # set current path to variable
    - if [ $current_path == "/home/cagauravbansal/repositories/registrationwalanew" ]; then export DEPLOYPATH=/home/cagauravbansal/registrationwalanew/; fi;
    - if [ $current_path == "/home4/ajaymaur/repositories/registrationwalanew" ]; then export DEPLOYPATH=/home4/ajaymaur/registrationwalanew/; fi;
    - /bin/cp -R * $DEPLOYPATH
